capture:
  interval: 0.1
  method: nvidia
label:
  background: rgba(0, 0, 0, 150)
  background_color: rgba(0, 0, 0, 150)
  border_radius: 2px
  font_family: Microsoft YaHei
  font_size: 14
  height: 20
  min_width: 200
  opacity: 0.8
  padding: 2px 5px
  text_color: white
logger:
  filename: app.log
  format: '[%(asctime)s] [%(levelname)s] %(message)s'
  level: DEBUG
  time_format: '%Y-%m-%d %H:%M:%S'
  type: qt
paths:
  assets: resources/assets
  config: resources/config
  logs: logs
  temp: temp
  templates: resources/templates
recognition:
  threshold: 0.5
screen:
  height: 1440
  width: 2560
window:
  height: 600
  opacity: 1.0
  width: 600
